# Site settings
title: Panos Galatis
email: pgalatis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Homepage of Panos Galatis
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pgalat.is" # the base hostname & protocol for your site
github_username:  pgalatis

# Plugins
plugins:
  - jekyll-sitemap

# Build settings
markdown: kramdown

permalink: pretty
paginate: 2
highlighter: rouge
gems: 
  - [jekyll-paginate]
  - jekyll-sitemap

excerpt_separator: <!--more-->
